apiVersion: apps/v1
kind: Deployment
metadata:
  name: miapp-deployment
  labels:
    app: nodejs-app
spec:
  replicas: 3  # Número de réplicas que se ejecutarán
  selector:
    matchLabels:
      app: nodejs-app
  template:
    metadata:
      labels:
        app: nodejs-app
    spec:
      containers:
      - name: nodejs-app
        image: jorgesm15/nodejs-app:latest  # Imagen de Docker con su tag
        ports:
        - containerPort: 8080
